export const Menu =[
    {
        id:1,
        title:"Home",
        link:"#home"
    },
    {
        id:2,
        title:"About",
        link:"#about"
    },
    {
        id:3,
        title:"Service",
        link:"#service"
    },
    {
        id:4,
        title:"Blog",
        link:"#blog"
    },
    {
        id:5,
        title:"Testimonials",
        link:"#testimonials"
    }
]